name: imagesearch
channels:
  - defaults
dependencies:
  - ca-certificates=2019.8.28=0
  - certifi=2019.9.11=py37_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - openssl=1.1.1d=h1de35cc_1
  - pip=19.2.3=py37_0
  - python=3.7.3=h359304d_0
  - readline=7.0=h1de35cc_5
  - setuptools=41.2.0=py37_0
  - sqlite=3.29.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h1de35cc_4
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - absl-py==0.8.0
    - astor==0.8.0
    - cycler==0.10.0
    - decorator==4.4.0
    - gast==0.3.2
    - google-pasta==0.1.7
    - grpcio==1.24.0
    - h5py==2.10.0
    - imageio==2.5.0
    - joblib==0.13.2
    - keras==2.3.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - kiwisolver==1.1.0
    - markdown==3.1.1
    - matplotlib==3.1.1
    - networkx==2.3
    - numpy==1.17.2
    - pillow==6.1.0
    - protobuf==3.9.2
    - pyparsing==2.4.2
    - pyqt5==5.13.1
    - pyqt5-sip==4.19.19
    - python-dateutil==2.8.0
    - pywavelets==1.0.3
    - pyyaml==5.1.2
    - scikit-image==0.15.0
    - scikit-learn==0.21.3
    - scipy==1.3.1
    - six==1.12.0
    - tensorboard==1.14.0
    - tensorflow==1.14.0
    - tensorflow-estimator==1.14.0
    - termcolor==1.1.0
    - werkzeug==0.16.0
    - wrapt==1.11.2
prefix: /Users/romuere/anaconda3/envs/pycbir
